package CumprimentadorApp;

/**
* CumprimentadorApp/CumprimentadorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cumprimentador.idl
* Friday, September 18, 2026 10:43:42 PM UTC
*/

public final class CumprimentadorHolder implements org.omg.CORBA.portable.Streamable
{
  public CumprimentadorApp.Cumprimentador value = null;

  public CumprimentadorHolder ()
  {
  }

  public CumprimentadorHolder (CumprimentadorApp.Cumprimentador initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CumprimentadorApp.CumprimentadorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CumprimentadorApp.CumprimentadorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CumprimentadorApp.CumprimentadorHelper.type ();
  }

}
