package CumprimentadorApp;


/**
* CumprimentadorApp/CumprimentadorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cumprimentador.idl
* Friday, September 18, 2026 10:43:42 PM UTC
*/

public interface CumprimentadorOperations 
{
  String cumprimentar ();
} // interface CumprimentadorOperations
