package CumprimentadorApp;


/**
* CumprimentadorApp/Cumprimentador.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cumprimentar.idl
* Friday, September 18, 2026 9:11:15 PM UTC
*/

public interface Cumprimentador extends CumprimentadorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Cumprimentador
